apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: server
    image: rkpatra/sbh:ns
    volumeMounts:
    - name: shared-data
      mountPath: /server-dir

  - name: nginx
    image: rkpatra/nginx:ns
    volumeMounts:
    - name: shared-data
      mountPath: /nginx-dir
    